loadingscreenupdate(`Preparing card_dict`);
let active_messages = [];
let timed_count_change = [];
let expireTimer = null;
const activeBars = new Set();
(function animate() {
  const now = performance.now();

  for (const bar of activeBars) {
    const elapsed = now - bar.start;
    const progress = Math.min(elapsed / bar.duration, 1);

    bar.fill.style.width = `${100 - progress * 100}%`;

    if (progress >= 1) {
      activeBars.delete(bar);
    }
  }

  requestAnimationFrame(animate);
})();
const SYNODIC_MONTH = 29.530588853 * 86400000; // ms
const KNOWN_NEW_MOON = 947182440000; // Date.UTC(2000, 0, 6, 18, 14, 0); // 2000-01-06 18:14 UTC
function getNearestNewMoon(hoursBefore = 0) {
  const now = Clock.now();

  const cycles = Math.round((now - KNOWN_NEW_MOON) / SYNODIC_MONTH);

  return KNOWN_NEW_MOON + cycles * SYNODIC_MONTH - hoursBefore * 3600000;
}
function getNextNewMoon(hoursBefore = 0) {
  const now = Clock.now();

  const cycles = Math.ceil((now - KNOWN_NEW_MOON) / SYNODIC_MONTH);

  return KNOWN_NEW_MOON + cycles * SYNODIC_MONTH - hoursBefore * 3600000;
}
// past or future:
function getNearestFullMoon(hoursBefore = 0) {
  const now = Clock.now();

  const fullBase = KNOWN_NEW_MOON + SYNODIC_MONTH / 2;

  const cycles = Math.round((now - fullBase) / SYNODIC_MONTH);

  return fullBase + cycles * SYNODIC_MONTH - hoursBefore * 3600000;
}
// only future:
function getNextFullMoon(hoursBefore = 0) {
  const now = Clock.now();

  const fullBase = KNOWN_NEW_MOON + SYNODIC_MONTH / 2;

  const cycles = Math.ceil((now - fullBase) / SYNODIC_MONTH);

  return fullBase + cycles * SYNODIC_MONTH - hoursBefore * 3600000;
}
var card_dict_base = [
  {
    name: "Mysterious Elf",
    id: "142",
    deck: "neutral",
    row: "close",
    strength: "0",
    ability: "hero spy",
    filename: "mysterious_elf",
    count: "1",
  },
  {
    name: "Decoy",
    id: "1",
    deck: "special",
    row: "",
    strength: "0",
    ability: "decoy",
    filename: "decoy",
    count: "3",
    isDecoy: true,
    isDecoyMath: true,
  },
  {
    name: "Biting Frost",
    id: "4",
    deck: "weather",
    row: "",
    strength: "",
    ability: "frost",
    filename: "frost",
    count: "3",
  },
  {
    name: "Cirilla Fiona Elen Riannon",
    id: "139",
    deck: "neutral",
    row: "close",
    strength: "15",
    ability: "hero",
    filename: "ciri",
    count: "1",
  },
  {
    name: "Clear Weather",
    id: "7",
    deck: "weather",
    row: "",
    strength: "",
    ability: "clear",
    filename: "clear",
    count: "2",
  },
  {
    name: "Commander's Horn",
    id: "2",
    deck: "special",
    row: "",
    strength: "",
    ability: "horn",
    filename: "horn",
    count: "3",
    isSide: true,
    info: "Keep it at this index of array or game will break (Good Desing btw)",
  },
  {
    name: "Dandelion",
    id: "11",
    deck: "neutral",
    row: "close",
    strength: "2",
    ability: "horn",
    filename: "dandelion",
    count: "1",
  },
  {
    name: "Emiel Regis Rohellec Terzieff",
    id: "",
    deck: "neutral",
    row: "close",
    strength: "5",
    ability: "",
    filename: "emiel",
    count: "1",
  },
  {
    name: "Godling",
    id: "Decoy2",
    deck: "monsters",
    row: "NaR",
    strength: "8",
    ability: "hero decoy2",
    filename: "custom!Decoy2",
    customassets: {
      lg: {
        hero: true,
        ability: "decoy2",
        name: "Godling",
        desc: "Nobody expects an Godling here!",
        txt_timed_a: false,
      },
      sm: {
        type: "url", // url/build/timed
        build: [],
        url: "img/sm/monsters_godling_decoy.jpg",
        timed: [],
      },
    },
    count: "1",
    isDecoy: true,
    isDecoyMath: false,
  },
  {
    name: "Geralt of Rivia",
    id: "138",
    deck: "neutral",
    row: "close",
    strength: "15",
    ability: "hero",
    filename: "geralt",
    count: "1",
  },
  {
    name: "Impenetrable Fog",
    id: "5",
    deck: "weather",
    row: "",
    strength: "",
    ability: "fog",
    filename: "fog",
    count: "3",
  },
  {
    name: "Scorch",
    id: "3",
    deck: "special",
    row: "",
    strength: "",
    ability: "scorch",
    filename: "scorch",
    count: "3",
    isScorch: true,
  },
  {
    name: "Torrential Rain",
    id: "6",
    deck: "weather",
    row: "",
    strength: "",
    ability: "rain",
    filename: "rain",
    count: "2",
  },
  {
    name: "Triss Merigold",
    id: "141",
    deck: "neutral",
    row: "close",
    strength: "7",
    ability: "hero",
    filename: "triss",
    count: "1",
  },
  {
    name: "Vesemir",
    id: "9",
    deck: "neutral",
    row: "close",
    strength: "6",
    ability: "",
    filename: "vesemir",
    count: "1",
  },
  {
    name: "Villentretenmerth",
    id: "8",
    deck: "neutral",
    row: "close",
    strength: "7",
    ability: "scorch_c",
    filename: "villen",
    count: "1",
  },
  {
    name: "Yennefer of Vengerberg",
    id: "140",
    deck: "neutral",
    row: "ranged",
    strength: "7",
    ability: "hero medic_n",
    filename: "yennefer",
    count: "1",
  },
  {
    name: "Zoltan Chivay",
    id: "10",
    deck: "neutral",
    row: "close",
    strength: "5",
    ability: "",
    filename: "zoltan",
    count: "1",
  },
  {
    name: "Olgierd von Everec",
    id: "",
    deck: "neutral",
    row: "agile",
    strength: "6",
    ability: "morale",
    filename: "olgierd",
    count: "1",
  },
  {
    name: "Gaunter O'Dimm",
    id: "",
    deck: "neutral",
    row: "siege",
    strength: "2",
    ability: "muster",
    filename: "gaunter_odimm",
    count: "1",
  },
  {
    name: "Gaunter O'Dimm - Darkness",
    id: "",
    deck: "neutral",
    row: "ranged",
    strength: "4",
    ability: "muster",
    filename: "gaunter_odimm_darkness",
    count: "3",
  },
  {
    name: "Cow",
    id: "",
    deck: "neutral",
    row: "ranged",
    strength: "0",
    ability: "avenger DontPickMeUp",
    filename: "cow",
    count: "1",
  },
  {
    name: "Bovine Defense Force",
    id: "",
    deck: "neutral",
    row: "close",
    strength: "8",
    ability: "",
    filename: "chort",
    count: "0",
    avenger: "cow",
  },
  {
    name: "Foltest - King of Temeria",
    id: "5",
    deck: "realms",
    row: "leader",
    strength: "",
    ability: "foltest_king",
    filename: "foltest_silver",
    count: "1",
  },
  {
    name: "Foltest - Lord Commander of the North",
    id: "8",
    deck: "realms",
    row: "leader",
    strength: "",
    ability: "foltest_lord",
    filename: "foltest_gold",
    count: "1",
  },
  {
    name: "Foltest - The Siegemaster",
    id: "6",
    deck: "realms",
    row: "leader",
    strength: "",
    ability: "foltest_siegemaster",
    filename: "foltest_copper",
    count: "1",
  },
  {
    name: "Foltest - The Steel-Forged",
    id: "7",
    deck: "realms",
    row: "leader",
    strength: "",
    ability: "foltest_steelforged",
    filename: "foltest_bronze",
    count: "1",
  },
  {
    name: "Foltest - Son of Medell",
    id: "foltest_son_of_medell",
    deck: "realms",
    row: "leader",
    strength: "",
    ability: "foltest_son",
    filename: "foltest_son_of_medell",
    count: "1",
  },
  {
    name: "Ballista",
    id: "79",
    deck: "realms",
    row: "siege",
    strength: "6",
    ability: "",
    filename: "ballista",
    count: "1",
  },
  {
    name: "Blue Stripes Commando",
    id: "92",
    deck: "realms",
    row: "close",
    strength: "4",
    ability: "bond",
    filename: "blue_stripes",
    count: "3",
  },
  {
    name: "Catapult",
    id: "75",
    deck: "realms",
    row: "siege",
    strength: "8",
    ability: "bond",
    filename: "catapult_1",
    count: "2",
  },
  {
    name: "Crinfrid Reavers Dragon Hunter",
    id: "87",
    deck: "realms",
    row: "ranged",
    strength: "5",
    ability: "bond",
    filename: "crinfrid",
    count: "3",
  },
  {
    name: "Dethmold",
    id: "76",
    deck: "realms",
    row: "ranged",
    strength: "6",
    ability: "",
    filename: "dethmold",
    count: "1",
  },
  {
    name: "Dun Banner Medic",
    id: "88",
    deck: "realms",
    row: "siege",
    strength: "5",
    ability: "medic",
    filename: "banner_nurse",
    count: "1",
  },
  {
    name: "Esterad Thyssen",
    id: "11",
    deck: "realms",
    row: "close",
    strength: "10",
    ability: "hero",
    filename: "esterad",
    count: "1",
  },
  {
    name: "John Natalis",
    id: "10",
    deck: "realms",
    row: "close",
    strength: "10",
    ability: "hero",
    filename: "natalis",
    count: "1",
  },
  //  {
  //    name: "Kaedweni Siege Expert",
  //    id: "98",
  //    deck: "realms",
  //    row: "siege",
  //   strength: "1",
  //   ability: "morale",
  //    filename: "kaedwen_siege",
  //   count: "0",
  // },
  {
    name: "Kaedweni Siege Expert",
    id: "99",
    deck: "realms",
    row: "siege",
    strength: "1",
    ability: "morale",
    filename: "kaedwen_siege_1",
    count: "3",
  },
  //  {
  //   name: "Kaedweni Siege Expert",
  //   id: "100",
  //   deck: "realms",
  //   row: "siege",
  //   strength: "1",
  //   ability: "morale",
  //   filename: "kaedwen_siege_2",
  //   count: "0",
  // },
  {
    name: "Keira Metz",
    id: "84",
    deck: "realms",
    row: "ranged",
    strength: "5",
    ability: "",
    filename: "keira",
    count: "1",
  },
  {
    name: "Philippa Eilhart",
    id: "12",
    deck: "realms",
    row: "ranged",
    strength: "10",
    ability: "hero",
    filename: "philippa",
    count: "1",
  },
  {
    name: "Poor Fucking Infantry",
    id: "95",
    deck: "realms",
    row: "close",
    strength: "1",
    ability: "bond",
    filename: "poor_infantry",
    count: "4",
  },
  {
    name: "Prince Stennis",
    id: "86",
    deck: "realms",
    row: "close",
    strength: "5",
    ability: "spy",
    filename: "stennis",
    count: "1",
  },
  //  {
  //    name: "Redanian Foot Soldier",
  //   id: "96",
  //   deck: "realms",
  // row: "close",
  //  strength: "1",
  // ability: "",
  //    filename: "redania",
  //    count: "0",
  //  },
  {
    name: "Redanian Foot Soldier",
    id: "97",
    deck: "realms",
    row: "close",
    strength: "1",
    ability: "",
    filename: "redania_1",
    count: "2",
  },
  {
    name: "Sheldon Skaggs",
    id: "91",
    deck: "realms",
    row: "ranged",
    strength: "4",
    ability: "",
    filename: "sheldon",
    count: "1",
  },
  {
    name: "Siege Tower",
    id: "81",
    deck: "realms",
    row: "siege",
    strength: "6",
    ability: "",
    filename: "siege_tower",
    count: "1",
  },
  {
    name: "Siegfried of Denesle",
    id: "83",
    deck: "realms",
    row: "close",
    strength: "5",
    ability: "",
    filename: "siegfried",
    count: "1",
  },
  {
    name: "Sigismund Dijkstra",
    id: "89",
    deck: "realms",
    row: "close",
    strength: "4",
    ability: "spy",
    filename: "dijkstra",
    count: "1",
  },
  {
    name: "Síle de Tansarville",
    id: "85",
    deck: "realms",
    row: "ranged",
    strength: "5",
    ability: "",
    filename: "sheala",
    count: "1",
  },
  {
    name: "Thaler",
    id: "94",
    deck: "realms",
    row: "siege",
    strength: "1",
    ability: "spy",
    filename: "thaler",
    count: "1",
  },
  {
    name: "Sabrina Glevissig",
    id: "90",
    deck: "realms",
    row: "ranged",
    strength: "4",
    ability: "",
    filename: "sabrina",
    count: "1",
  },
  {
    name: "Vernon Roche",
    id: "9",
    deck: "realms",
    row: "close",
    strength: "10",
    ability: "hero",
    filename: "vernon",
    count: "1",
  },
  {
    name: "Ves",
    id: "82",
    deck: "realms",
    row: "close",
    strength: "5",
    ability: "",
    filename: "ves",
    count: "1",
  },
  {
    name: "Yarpen Zigrin",
    id: "93",
    deck: "realms",
    row: "close",
    strength: "2",
    ability: "",
    filename: "yarpen",
    count: "1",
  },
  //  {
  //    name: "Trebuchet",
  //    id: "77",
  //    deck: "realms",
  //    row: "siege",
  //    strength: "6",
  //    ability: "",
  //    filename: "trebuchet",
  //    count: "0",
  //  },
  {
    name: "Trebuchet",
    id: "78",
    deck: "realms",
    row: "siege",
    strength: "6",
    ability: "",
    filename: "trebuchet_1",
    count: "2",
  },
  {
    name: "Emhyr var Emreis - His Imperial Majesty",
    id: "1",
    deck: "nilfgaard",
    row: "leader",
    strength: "",
    ability: "emhyr_imperial",
    filename: "emhyr_copper",
    count: "1",
  },
  //   {
  //     "name": "Emhyr var Emreis - Emperor of Nilfgaard",
  //     "id": "2",
  //     "deck": "nilfgaard",
  //     "row": "leader",
  //     "strength": "",
  //     "ability": "emhyr_emperor",
  //     "filename": "emhyr_bronze",
  //     "count": "1"
  //  },
  {
    name: "Emhyr var Emreis - the White Flame",
    id: "3",
    deck: "nilfgaard",
    row: "leader",
    strength: "",
    ability: "emhyr_whiteflame2",
    filename: "emhyr_silver",
    count: "1",
  },
  {
    name: "Emhyr var Emreis - The Relentless",
    id: "4",
    deck: "nilfgaard",
    row: "leader",
    strength: "",
    ability: "emhyr_relentless",
    filename: "emhyr_gold",
    count: "1",
  },
  {
    name: "Emhyr var Emreis - Invader of the North",
    id: "emhyr_invader_of_the_north",
    deck: "nilfgaard",
    row: "leader",
    strength: "",
    ability: "emhyr_invader",
    filename: "emhyr_invader_of_the_north",
    count: "1",
  },
  {
    name: "Albrich",
    id: "68",
    deck: "nilfgaard",
    row: "ranged",
    strength: "2",
    ability: "",
    filename: "albrich",
    count: "1",
  },
  {
    name: "Assire var Anahid",
    id: "52",
    deck: "nilfgaard",
    row: "ranged",
    strength: "6",
    ability: "",
    filename: "assire",
    count: "1",
  },
  //  {
  //  name: "Black Infantry Archer",
  //   id: "47",
  //  deck: "nilfgaard",
  //   row: "ranged",
  //   strength: "10",
  //   ability: "",
  //   filename: "black_archer",
  //   count: "0",
  //  },
  {
    name: "Black Infantry Archer",
    id: "48",
    deck: "nilfgaard",
    row: "ranged",
    strength: "10",
    ability: "",
    filename: "black_archer_1",
    count: "2",
  },
  {
    name: "Cahir Mawr Dyffryn aep Ceallach",
    id: "54",
    deck: "nilfgaard",
    row: "close",
    strength: "6",
    ability: "",
    filename: "cahir",
    count: "1",
  },
  {
    name: "Cynthia",
    id: "60",
    deck: "nilfgaard",
    row: "ranged",
    strength: "4",
    ability: "",
    filename: "cynthia",
    count: "1",
  },
  {
    name: "Etolian Auxiliary Archers",
    id: "72",
    deck: "nilfgaard",
    row: "ranged",
    strength: "1",
    ability: "medic",
    filename: "archer_support",
    count: "2",
  },
  // {
  // name: "Etolian Auxiliary Archers",
  //  id: "73",
  //  deck: "nilfgaard",
  //  row: "ranged",
  //   strength: "1",
  //  ability: "medic",
  //  filename: "archer_support_1",
  //  count: "0",
  // },
  {
    name: "Fringilla Vigo",
    id: "53",
    deck: "nilfgaard",
    row: "ranged",
    strength: "6",
    ability: "",
    filename: "fringilla",
    count: "1",
  },
  {
    name: "Heavy Zerrikanian Fire Scorpion",
    id: "49",
    deck: "nilfgaard",
    row: "siege",
    strength: "10",
    ability: "",
    filename: "heavy_zerri",
    count: "1",
  },
  {
    name: "Impera Brigade Guard",
    id: "67",
    deck: "nilfgaard",
    row: "close",
    strength: "3",
    ability: "bond",
    filename: "imperal_brigade",
    count: "4",
  },
  {
    name: "Letho of Gulet",
    id: "147",
    deck: "nilfgaard",
    row: "close",
    strength: "10",
    ability: "hero",
    filename: "letho",
    count: "1",
  },
  {
    name: "Menno Coehoorn",
    id: "148",
    deck: "nilfgaard",
    row: "close",
    strength: "10",
    ability: "hero medic",
    filename: "menno",
    count: "1",
  },
  {
    name: "Morteisen",
    id: "64",
    deck: "nilfgaard",
    row: "close",
    strength: "3",
    ability: "",
    filename: "morteisen",
    count: "1",
  },
  {
    name: "Morvran Voorhis",
    id: "149",
    deck: "nilfgaard",
    row: "siege",
    strength: "10",
    ability: "hero",
    filename: "moorvran",
    count: "1",
  },
  {
    name: "Nausicaa Cavalry Rider",
    id: "71",
    deck: "nilfgaard",
    row: "close",
    strength: "2",
    ability: "bond",
    filename: "nauzicaa_2",
    count: "3",
  },
  {
    name: "Puttkammer",
    id: "66",
    deck: "nilfgaard",
    row: "ranged",
    strength: "3",
    ability: "",
    filename: "puttkammer",
    count: "1",
  },
  {
    name: "Rainfarn",
    id: "61",
    deck: "nilfgaard",
    row: "close",
    strength: "4",
    ability: "",
    filename: "rainfarn",
    count: "1",
  },
  {
    name: "Renuald aep Matsen",
    id: "56",
    deck: "nilfgaard",
    row: "ranged",
    strength: "5",
    ability: "",
    filename: "renuald",
    count: "1",
  },
  {
    name: "Rotten Mangonel",
    id: "65",
    deck: "nilfgaard",
    row: "siege",
    strength: "3",
    ability: "",
    filename: "rotten",
    count: "1",
  },
  {
    name: "Shilard Fitz-Oesterlen",
    id: "51",
    deck: "nilfgaard",
    row: "close",
    strength: "7",
    ability: "spy",
    filename: "shilard",
    count: "1",
  },
  {
    name: "Siege Engineer",
    id: "55",
    deck: "nilfgaard",
    row: "siege",
    strength: "6",
    ability: "",
    filename: "siege_engineer",
    count: "1",
  },
  {
    name: "Siege Technician",
    id: "74",
    deck: "nilfgaard",
    row: "siege",
    strength: "0",
    ability: "medic",
    filename: "siege_support",
    count: "1",
  },
  {
    name: "Stefan Skellen",
    id: "50",
    deck: "nilfgaard",
    row: "close",
    strength: "9",
    ability: "spy",
    filename: "stefan",
    count: "1",
  },
  {
    name: "Sweers",
    id: "69",
    deck: "nilfgaard",
    row: "ranged",
    strength: "2",
    ability: "",
    filename: "sweers",
    count: "1",
  },
  {
    name: "Tibor Eggebracht",
    id: "150",
    deck: "nilfgaard",
    row: "ranged",
    strength: "10",
    ability: "hero",
    filename: "tibor",
    count: "1",
  },
  {
    name: "Vanhemar",
    id: "62",
    deck: "nilfgaard",
    row: "ranged",
    strength: "4",
    ability: "",
    filename: "vanhemar",
    count: "1",
  },
  {
    name: "Vattier de Rideaux",
    id: "63",
    deck: "nilfgaard",
    row: "close",
    strength: "4",
    ability: "spy",
    filename: "vattier",
    count: "1",
  },
  {
    name: "Vreemde",
    id: "70",
    deck: "nilfgaard",
    row: "close",
    strength: "2",
    ability: "",
    filename: "vreemde",
    count: "1",
  },
  {
    name: "Young Emissary",
    id: "58",
    deck: "nilfgaard",
    row: "close",
    strength: "5",
    ability: "bond",
    filename: "young_emissary",
    count: "2",
  },
  //  {
  ///    name: "Young Emissary",
  //   id: "59",
  //   deck: "nilfgaard",
  //   row: "close",
  //   strength: "5",
  //   ability: "bond",
  //   filename: "young_emissary_1",
  //   count: "0",
  //  },
  {
    name: "Zerrikanian Fire Scorpion",
    id: "57",
    deck: "nilfgaard",
    row: "siege",
    strength: "5",
    ability: "",
    filename: "zerri",
    count: "1",
  },
  {
    name: "Eredin - Commander of the Red Riders",
    id: "134",
    deck: "monsters",
    row: "leader",
    strength: "",
    ability: "eredin_commander",
    filename: "eredin_bronze",
    count: "1",
  },
  {
    name: "Eredin - Bringer of Death",
    id: "136",
    deck: "monsters",
    row: "leader",
    strength: "",
    ability: "eredin_bringer_of_death",
    filename: "eredin_silver",
    count: "1",
  },
  {
    name: "Eredin - Destroyer of Worlds",
    id: "137",
    deck: "monsters",
    row: "leader",
    strength: "",
    ability: "eredin_destroyer",
    filename: "eredin_gold",
    count: "1",
  },
  {
    name: "Eredin - King of the Wild Hunt",
    id: "135",
    deck: "monsters",
    row: "leader",
    strength: "",
    ability: "eredin_king", // SEEMS TO BE BROKEN IN ASYNC EVENT, AS IT DONT DEFINE CARD (DAMM IT)
    filename: "eredin_copper",
    count: "1",
  },
  {
    name: "Eredin Bréacc Glas - The Treacherous",
    id: "eredin_the_treacherous",
    deck: "monsters",
    row: "leader",
    strength: "",
    ability: "eredin_treacherous",
    filename: "eredin_the_treacherous",
    count: "1",
  },
  //  {
  //    name: "Arachas ",
  //   id: "27",
  //   deck: "monsters",
  //   row: "close",
  //    strength: "4",
  //   ability: "muster",
  //   filename: "arachas",
  //   count: "0",
  // },
  {
    name: "Arachas ",
    id: "28",
    deck: "monsters",
    row: "close",
    strength: "4",
    ability: "muster",
    filename: "arachas_1",
    count: "3",
  },
  // {
  //   name: "Arachas ",
  //   id: "29",
  //   deck: "monsters",
  //   row: "close",
  //   strength: "4",
  //  ability: "muster",
  //   filename: "arachas_2",
  //   count: "0",
  // },
  {
    name: "Arachas- Behemoth",
    id: "15",
    deck: "monsters",
    row: "siege",
    strength: "6",
    ability: "muster",
    filename: "arachas_behemoth",
    count: "1",
  },
  {
    name: "Botchling",
    id: "26",
    deck: "monsters",
    row: "close",
    strength: "4",
    ability: "",
    filename: "poroniec",
    count: "1",
  },
  {
    name: "Celaeno Harpy",
    id: "38",
    deck: "monsters",
    row: "agile",
    strength: "2",
    ability: "",
    filename: "celaeno_harpy",
    count: "1",
  },
  {
    name: "Cockatrice",
    id: "36",
    deck: "monsters",
    row: "ranged",
    strength: "2",
    ability: "",
    filename: "cockatrice",
    count: "1",
  },
  {
    name: "Crone - Brewess",
    id: "16",
    deck: "monsters",
    row: "close",
    strength: "6",
    ability: "muster",
    filename: "witch_velen",
    count: "1",
  },
  {
    name: "Crone - Weavess",
    id: "17",
    deck: "monsters",
    row: "close",
    strength: "6",
    ability: "muster",
    filename: "witch_velen_1",
    count: "1",
  },
  {
    name: "Crone - Whispess",
    id: "18",
    deck: "monsters",
    row: "close",
    strength: "6",
    ability: "muster",
    filename: "witch_velen_2",
    count: "1",
  },
  {
    name: "Draug",
    id: "143",
    deck: "monsters",
    row: "close",
    strength: "10",
    ability: "hero",
    filename: "draug",
    count: "1",
  },
  {
    name: "Earth Elemental",
    id: "12",
    deck: "monsters",
    row: "siege",
    strength: "6",
    ability: "",
    filename: "earth_elemental",
    count: "1",
  },
  {
    name: "Endrega",
    id: "34",
    deck: "monsters",
    row: "ranged",
    strength: "2",
    ability: "",
    filename: "endrega",
    count: "1",
  },
  {
    name: "Fiend",
    id: "13",
    deck: "monsters",
    row: "close",
    strength: "6",
    ability: "",
    filename: "fiend",
    count: "1",
  },
  {
    name: "Fire Elemental",
    id: "14",
    deck: "monsters",
    row: "siege",
    strength: "6",
    ability: "",
    filename: "fire_elemental",
    count: "1",
  },
  {
    name: "Foglet",
    id: "39",
    deck: "monsters",
    row: "close",
    strength: "2",
    ability: "",
    filename: "fogling",
    count: "1",
  },
  {
    name: "Forktail",
    id: "19",
    deck: "monsters",
    row: "close",
    strength: "5",
    ability: "",
    filename: "forktail",
    count: "1",
  },
  {
    name: "Frightener",
    id: "23",
    deck: "monsters",
    row: "close",
    strength: "5",
    ability: "",
    filename: "frightener",
    count: "1",
  },
  {
    name: "Gargoyle",
    id: "37",
    deck: "monsters",
    row: "ranged",
    strength: "2",
    ability: "",
    filename: "gargoyle",
    count: "1",
  },
  {
    name: "Ghoul",
    id: "44",
    deck: "monsters",
    row: "close",
    strength: "1",
    ability: "muster",
    filename: "ghoul",
    count: "3",
  },
  // {
  //   name: "Ghoul",
  //    id: "45",
  //    deck: "monsters",
  //    row: "close",
  //    strength: "1",
  //   ability: "muster",
  //    filename: "ghoul_1",
  //    count: "0",
  // },
  //  {
  //   name: "Ghoul",
  //   id: "46",
  //   deck: "monsters",
  //   row: "close",
  //   strength: "1",
  //   ability: "muster",
  //    filename: "ghoul_2",
  //    count: "0",
  // },
  {
    name: "Grave Hag",
    id: "25",
    deck: "monsters",
    row: "ranged",
    strength: "5",
    ability: "",
    filename: "gravehag",
    count: "1",
  },
  {
    name: "Griffin",
    id: "21",
    deck: "monsters",
    row: "close",
    strength: "5",
    ability: "",
    filename: "gryffin",
    count: "1",
  },
  {
    name: "Harpy",
    id: "35",
    deck: "monsters",
    row: "agile",
    strength: "2",
    ability: "",
    filename: "harpy",
    count: "1",
  },
  {
    name: "Ice Giant",
    id: "24",
    deck: "monsters",
    row: "siege",
    strength: "5",
    ability: "",
    filename: "frost_giant",
    count: "1",
  },
  {
    name: "Imlerith",
    id: "144",
    deck: "monsters",
    row: "close",
    strength: "10",
    ability: "hero",
    filename: "imlerith",
    count: "1",
  },
  {
    name: "Kayran",
    id: "146",
    deck: "monsters",
    row: "agile",
    strength: "8",
    ability: "hero morale",
    filename: "kayran",
    count: "1",
  },
  {
    name: "Leshen",
    id: "145",
    deck: "monsters",
    row: "ranged",
    strength: "10",
    ability: "hero",
    filename: "leshen",
    count: "1",
    avenger: "eskel",
  },
  {
    name: "Nekker",
    id: "41",
    deck: "monsters",
    row: "close",
    strength: "2",
    ability: "muster",
    filename: "nekker",
    count: "3",
  },
  //  {
  //   name: "Nekker",
  ///   id: "42",
  //    deck: "monsters",
  //   row: "close",
  //   strength: "2",
  //   ability: "muster",
  //   filename: "nekker_1",
  //   count: "0",
  // },
  // {
  //   name: "Nekker",
  //   id: "43",
  //  deck: "monsters",
  //   row: "close",
  //   strength: "2",
  //  ability: "muster",
  //   filename: "nekker_2",
  //  count: "0",
  // },
  {
    name: "Plague Maiden",
    id: "20",
    deck: "monsters",
    row: "close",
    strength: "5",
    ability: "",
    filename: "mighty_maiden",
    count: "1",
  },
  {
    name: "Vampire - Bruxa",
    id: "33",
    deck: "monsters",
    row: "close",
    strength: "4",
    ability: "muster",
    filename: "bruxa",
    count: "1",
  },
  {
    name: "Vampire - Ekimmara",
    id: "30",
    deck: "monsters",
    row: "close",
    strength: "4",
    ability: "muster",
    filename: "ekkima",
    count: "1",
  },
  {
    name: "Vampire - Fleder",
    id: "31",
    deck: "monsters",
    row: "close",
    strength: "4",
    ability: "muster",
    filename: "fleder",
    count: "1",
  },
  {
    name: "Vampire - Garkain",
    id: "32",
    deck: "monsters",
    row: "close",
    strength: "4",
    ability: "muster",
    filename: "garkain",
    count: "1",
  },
  {
    name: "Vampire - Katakan",
    id: "",
    deck: "monsters",
    row: "close",
    strength: "5",
    ability: "muster",
    filename: "katakan",
    count: "1",
  },
  {
    name: "Werewolf",
    id: "22",
    deck: "monsters",
    row: "close",
    strength: "5",
    ability: "",
    filename: "werewolf",
    count: "1",
  },
  {
    name: "Wyvern",
    id: "40",
    deck: "monsters",
    row: "ranged",
    strength: "2",
    ability: "",
    filename: "wyvern",
    count: "1",
  },
  {
    name: "Toad",
    id: "",
    deck: "monsters",
    row: "ranged",
    strength: "7",
    ability: "scorch_r",
    filename: "toad",
    count: "1",
  },
  {
    name: "Francesca Findabair - Queen of Dol Blathanna",
    id: "13",
    deck: "scoiatael",
    row: "leader",
    strength: "",
    ability: "francesca_queen",
    filename: "francesca_silver",
    count: "1",
  },
  {
    name: "Francesca Findabair - the Beautiful",
    id: "14",
    deck: "scoiatael",
    row: "leader",
    strength: "",
    ability: "francesca_beautiful",
    filename: "francesca_gold",
    count: "1",
  },
  {
    name: "Francesca Findabair - Daisy of the Valley",
    id: "15",
    deck: "scoiatael",
    row: "leader",
    strength: "",
    ability: "francesca_daisy",
    filename: "francesca_copper",
    count: "1",
  },
  {
    name: "Francesca Findabair - Pureblood Elf",
    id: "16",
    deck: "scoiatael",
    row: "leader",
    strength: "",
    ability: "francesca_pureblood",
    filename: "francesca_bronze",
    count: "1",
  },
  {
    name: "Francesca Findabair - Hope of the Aen Seidhe",
    id: "francesca_hope_of_the_aen_seidhe",
    deck: "scoiatael",
    row: "leader",
    strength: "",
    ability: "francesca_hope",
    filename: "francesca_hope_of_the_aen_seidhe",
    count: "1",
  },
  {
    name: "Ciaran aep Easnillien",
    id: "122",
    deck: "scoiatael",
    row: "agile",
    strength: "3",
    ability: "",
    filename: "ciaran",
    count: "1",
  },
  {
    name: "Barclay Els",
    id: "106",
    deck: "scoiatael",
    row: "agile",
    strength: "6",
    ability: "",
    filename: "barclay",
    count: "1",
  },
  {
    name: "Dennis Cranmer",
    id: "102",
    deck: "scoiatael",
    row: "close",
    strength: "6",
    ability: "",
    filename: "dennis",
    count: "1",
  },
  {
    name: "Dol Blathanna Archer",
    id: "121",
    deck: "scoiatael",
    row: "ranged",
    strength: "4",
    ability: "",
    filename: "dol_archer",
    count: "1",
  },
  //  {
  ///   name: "Dol Blathanna Scout",
  //    id: "107",
  //   deck: "scoiatael",
  //   row: "agile",
  //   strength: "6",
  //  ability: "",
  //  filename: "dol_infantry",
  //  count: "0",
  // },
  // {
  //  name: "Dol Blathanna Scout",
  //  id: "108",
  //   deck: "scoiatael",
  //  row: "agile",
  //   strength: "6",
  //   ability: "",
  //   filename: "dol_infantry_1",
  //   count: "0",
  // },
  {
    name: "Dol Blathanna Scout",
    id: "109",
    deck: "scoiatael",
    row: "agile",
    strength: "6",
    ability: "",
    filename: "dol_infantry_2",
    count: "3",
  },
  {
    name: "Dwarven Skirmisher",
    id: "123",
    deck: "scoiatael",
    row: "close",
    strength: "3",
    ability: "muster",
    filename: "dwarf",
    count: "3",
  },
  // {
  //   name: "Dwarven Skirmisher",
  //   id: "124",
  //   deck: "scoiatael",
  //   row: "close",
  //   strength: "3",
  //    ability: "muster",
  //    filename: "dwarf_1",
  //   count: "0",
  // },
  // {
  //   name: "Dwarven Skirmisher",
  //   id: "125",
  //   deck: "scoiatael",
  //    row: "close",
  //   strength: "3",
  //    ability: "muster",
  //   filename: "dwarf_2",
  //   count: "0",
  // },
  {
    name: "Eithné",
    id: "17",
    deck: "scoiatael",
    row: "ranged",
    strength: "10",
    ability: "hero",
    filename: "eithne",
    count: "1",
  },
  // {
  //   name: "Elven Skirmisher",
  //   id: "127",
  //   deck: "scoiatael",
  //   row: "ranged",
  //   strength: "2",
  //   ability: "muster",
  //   filename: "elf_skirmisher",
  //   count: "0",
  // },
  {
    name: "Elven Skirmisher",
    id: "128",
    deck: "scoiatael",
    row: "ranged",
    strength: "2",
    ability: "muster",
    filename: "elf_skirmisher_1",
    count: "3",
  },
  //  {
  //   name: "Elven Skirmisher",
  //   id: "129",
  //   deck: "scoiatael",
  //   row: "ranged",
  //   strength: "2",
  //   ability: "muster",
  //   filename: "elf_skirmisher_2",
  //  count: "0",
  //},
  {
    name: "Filavandrel aen Fidhail",
    id: "104",
    deck: "scoiatael",
    row: "agile",
    strength: "6",
    ability: "",
    filename: "filavandrel",
    count: "1",
  },
  //  {
  //   name: "Havekar Healer",
  //   id: "131",
  //   deck: "scoiatael",
  //    row: "ranged",
  //    strength: "0",
  //ability: "medic",
  // filename: "havekar_nurse",
  //  count: "0",
  // },
  // {
  //   name: "Havekar Healer",
  //   id: "132",
  //   deck: "scoiatael",
  //    row: "ranged",
  //    strength: "0",
  //   ability: "medic",
  //   filename: "havekar_nurse_1",
  //    count: "0",
  //  },
  {
    name: "Havekar Healer",
    id: "133",
    deck: "scoiatael",
    row: "ranged",
    strength: "0",
    ability: "medic",
    filename: "havekar_nurse_2",
    count: "3",
  },
  // {
  //   name: "Havekar Smuggler",
  //   id: "110",
  //   deck: "scoiatael",
  //   row: "close",
  //   strength: "5",
  //   ability: "muster",
  //   filename: "havekar_support",
  //   count: "0",
  // },
  // {
  //   name: "Havekar Smuggler",
  //   id: "111",
  //   deck: "scoiatael",
  //   row: "close",
  //   strength: "5",
  //   ability: "muster",
  //   filename: "havekar_support_1",
  //   count: "0",
  // },
  {
    name: "Havekar Smuggler",
    id: "112",
    deck: "scoiatael",
    row: "close",
    strength: "5",
    ability: "muster",
    filename: "havekar_support_2",
    count: "3",
  },
  {
    name: "Ida Emean aep Sivney",
    id: "103",
    deck: "scoiatael",
    row: "ranged",
    strength: "6",
    ability: "",
    filename: "ida",
    count: "1",
  },
  {
    name: "Iorveth",
    id: "20",
    deck: "scoiatael",
    row: "ranged",
    strength: "10",
    ability: "hero",
    filename: "iorveth",
    count: "1",
  },
  {
    name: "Isengrim Faoiltiarna",
    id: "19",
    deck: "scoiatael",
    row: "close",
    strength: "10",
    ability: "hero morale",
    filename: "isengrim",
    count: "1",
  },
  //  {
  //   name: "Mahakaman Defender",
  //   id: "115",
  //   deck: "scoiatael",
  //   row: "close",
  //   strength: "5",
  //   ability: "",
  //   filename: "mahakam",
  //   count: "0",
  // },
  // {
  //  name: "Mahakaman Defender",
  //  id: "116",
  //  deck: "scoiatael",
  //  row: "close",
  //  strength: "5",
  //    ability: "",
  //   filename: "mahakam_1",
  //    count: "0",
  //  },
  //  {
  //    name: "Mahakaman Defender",
  //  id: "117",
  //    deck: "scoiatael",
  //    row: "close",
  //   strength: "5",
  //   ability: "",
  //   filename: "mahakam_2",
  //   count: "0",
  // },
  //  {
  //   name: "Mahakaman Defender",
  //   id: "118",
  //   deck: "scoiatael",
  //   row: "close",
  //   strength: "5",
  //   ability: "",
  //   filename: "mahakam_3",
  //   count: "0",
  // },
  {
    name: "Mahakaman Defender",
    id: "119",
    deck: "scoiatael",
    row: "close",
    strength: "5",
    ability: "",
    filename: "mahakam_4",
    count: "5",
  },
  {
    name: "Milva",
    id: "101",
    deck: "scoiatael",
    row: "ranged",
    strength: "10",
    ability: "morale",
    filename: "milva",
    count: "1",
  },
  {
    name: "Riordain",
    id: "130",
    deck: "scoiatael",
    row: "ranged",
    strength: "1",
    ability: "",
    filename: "riordain",
    count: "1",
  },
  {
    name: "Saesenthessis",
    id: "18",
    deck: "scoiatael",
    row: "ranged",
    strength: "10",
    ability: "hero",
    filename: "saskia",
    count: "1",
  },
  {
    name: "Toruviel",
    id: "126",
    deck: "scoiatael",
    row: "ranged",
    strength: "2",
    ability: "",
    filename: "toruviel",
    count: "1",
  },
  {
    name: "Vrihedd Brigade Recruit",
    id: "120",
    deck: "scoiatael",
    row: "ranged",
    strength: "4",
    ability: "",
    filename: "vrihedd_cadet",
    count: "1",
  },
  //  {
  //   name: "Vrihedd Brigade Veteran",
  //   id: "113",
  //   deck: "scoiatael",
  //   row: "agile",
  //   strength: "5",
  //   ability: "",
  //   filename: "vrihedd_brigade",
  //   count: "0",
  //  },
  {
    name: "Vrihedd Brigade Veteran",
    id: "114",
    deck: "scoiatael",
    row: "agile",
    strength: "5",
    ability: "",
    filename: "vrihedd_brigade_1",
    count: "2",
  },
  {
    name: "Yaevinn",
    id: "105",
    deck: "scoiatael",
    row: "agile",
    strength: "6",
    ability: "",
    filename: "yaevinn",
    count: "1",
  },
  {
    name: "Berserker",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "4",
    ability: "berserker",
    filename: "berserker",
    count: "1",
  },
  {
    name: "Birna Bran",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "2",
    ability: "medic",
    filename: "birna",
    count: "1",
  },
  {
    name: "Blueboy Lugos",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "6",
    ability: "",
    filename: "blueboy",
    count: "1",
  },
  {
    name: "Cerys",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "10",
    ability: "hero muster",
    filename: "cerys",
    count: "1",
  },
  {
    name: "Clan Brokva Archer",
    id: "",
    deck: "skellige",
    row: "ranged",
    strength: "6",
    ability: "",
    filename: "brokva_archer",
    count: "2",
  },
  {
    name: "Clan Dimun Pirate",
    id: "",
    deck: "skellige",
    row: "ranged",
    strength: "6",
    ability: "scorch_r",
    filename: "dimun_pirate",
    count: "1",
  },
  //  {
  //    name: "Cerys - Clan Drummond Shield Maiden",
  //    id: "",
  //    deck: "skellige",
  //   row: "close",
  //   strength: "4",
  //   ability: "bond",
  //   filename: "shield_maiden",
  //   count: "0",
  // },
  //  {
  //   name: "Cerys - Clan Drummond Shield Maiden",
  //    id: "",
  ///    deck: "skellige",
  //   row: "close",
  //   strength: "4",
  //  ability: "bond",
  //  filename: "shield_maiden_1",
  //  count: "0",
  // },
  {
    name: "Cerys - Clan Drummond Shield Maiden",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "4",
    ability: "bond",
    filename: "shield_maiden_2",
    count: "3",
  },
  {
    name: "Clan Heymaey Skald",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "4",
    ability: "",
    filename: "heymaey",
    count: "1",
  },
  {
    name: "Clan Tordarroch Armorsmith",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "4",
    ability: "",
    filename: "tordarroch",
    count: "1",
  },
  {
    name: "Clan an Craite Warrior",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "6",
    ability: "bond",
    filename: "craite_warrior",
    count: "3",
  },
  {
    name: "Donar an Hindar",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "4",
    ability: "",
    filename: "donar",
    count: "1",
  },
  {
    name: "Draig Bon-Dhu",
    id: "",
    deck: "skellige",
    row: "siege",
    strength: "2",
    ability: "horn",
    filename: "draig",
    count: "1",
  },
  {
    name: "Ermion",
    id: "",
    deck: "skellige",
    row: "ranged",
    strength: "8",
    ability: "hero mardroeme",
    filename: "ermion",
    count: "1",
  },
  {
    name: "Hemdall",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "11",
    ability: "hero",
    filename: "hemdall",
    count: "0",
    avenger: "kambi",
  },
  {
    name: "Hjalmar",
    id: "",
    deck: "skellige",
    row: "ranged",
    strength: "10",
    ability: "hero",
    filename: "hjalmar",
    count: "1",
  },
  {
    name: "Holger Blackhand",
    id: "",
    deck: "skellige",
    row: "siege",
    strength: "4",
    ability: "",
    filename: "holger",
    count: "1",
  },
  {
    name: "Kambi",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "0",
    ability: "avenger DontPickMeUp",
    filename: "kambi",
    count: "1",
  },
  {
    name: "Light Longship",
    id: "",
    deck: "skellige",
    row: "ranged",
    strength: "4",
    ability: "muster",
    filename: "light_longship",
    count: "3",
  },
  {
    name: "Madman Lugos",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "6",
    ability: "",
    filename: "madmad_lugos",
    count: "1",
  },
  {
    name: "Mardroeme",
    id: "",
    deck: "special",
    row: "",
    strength: "",
    ability: "mardroeme",
    filename: "mardroeme",
    count: "3",
    isSide: true,
  },
  {
    name: "Olaf",
    id: "",
    deck: "skellige",
    row: "agile",
    strength: "12",
    ability: "morale",
    filename: "olaf",
    count: "1",
  },
  {
    name: "Skellige Storm",
    id: "",
    deck: "weather",
    row: "",
    strength: "",
    ability: "rain fog",
    filename: "storm",
    count: "3",
  },
  {
    name: "Svanrige",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "4",
    ability: "",
    filename: "svanrige",
    count: "1",
  },
  {
    name: "Transformed Vildkaarl",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "14",
    ability: "morale",
    filename: "vildkaarl",
    count: "0",
  },
  {
    name: "Transformed Young Vildkaarl",
    id: "",
    deck: "skellige",
    row: "ranged",
    strength: "8",
    ability: "bond",
    filename: "young_vildkaarl",
    count: "0",
  },
  {
    name: "Udalryk",
    id: "",
    deck: "skellige",
    row: "close",
    strength: "4",
    ability: "",
    filename: "udalryk",
    count: "1",
  },
  {
    name: "War Longship",
    id: "",
    deck: "skellige",
    row: "siege",
    strength: "6",
    ability: "bond",
    filename: "war_longship",
    count: "2",
  },
  {
    name: "Young Berserker",
    id: "",
    deck: "skellige",
    row: "ranged",
    strength: "2",
    ability: "berserker",
    filename: "young_berserker",
    count: "3",
  },
  {
    name: "Crach an Craite",
    id: "crach_an_craite",
    deck: "skellige",
    row: "leader",
    strength: "",
    ability: "crach_an_craite",
    filename: "crach_an_craite",
    count: "0",
  },
  {
    name: "King Bran",
    id: "king_bran",
    deck: "skellige",
    row: "leader",
    strength: "",
    ability: "king_bran",
    filename: "king_bran",
    count: "0",
  },
  {
    name: "Schirru",
    id: "",
    deck: "scoiatael",
    row: "siege",
    strength: "8",
    ability: "scorch_s",
    filename: "schirru",
    count: "1",
  },
  {
    name: "Gerry from the River",
    id: "151",
    deck: "skellige",
    row: "close",
    strength: "15",
    ability: "hero",
    filename: "gerry",
    count: "1",
  },

  // custom
  {
    name: "Letho - The Saboteur",
    id: "1001",
    deck: "neutral",
    row: "agile",
    strength: "-3",
    ability: "sabotage",
    filename: "lethosabotage",
    count: "1",
  },
  // neutral_aidhorn.jpg
  {
    name: "Horn of Support",
    id: "1002",
    deck: "neutral",
    row: "siege",
    strength: "0",
    ability: "hero aid",
    filename: "aidhorn",
    count: "1",
  },
  //  { //Yeah this card sucks
  //   name: "Jan Calveit: Calculated Recovery",
  //   id: "1003",
  //    deck: "nilfgaard",
  //    row: "leader",
  //    strength: "0",
  //   ability: "nilf_drawmaster",
  //   filename: "nilf_drawmaster",
  //   count: "1",
  // },
  {
    name: "Gaunter o'Dim",
    id: "1004-mon",
    deck: "monsters",
    row: "leader",
    strength: "0",
    ability: "gaunter_neutral_leader",
    filename: "Gaunter_Leader",
    count: "1",
  },
  {
    name: "Gaunter o'Dim",
    id: "1004-nilf",
    deck: "nilfgaard",
    row: "leader",
    strength: "0",
    ability: "gaunter_neutral_leader",
    filename: "Gaunter_Leader",
    count: "1",
  },
  {
    name: "Gaunter o'Dim",
    id: "1004-realms",
    deck: "realms",
    row: "leader",
    strength: "0",
    ability: "gaunter_neutral_leader",
    filename: "Gaunter_Leader",
    count: "1",
  },
  {
    name: "Gaunter o'Dim",
    id: "1004-scol",
    deck: "scoiatael",
    row: "leader",
    strength: "0",
    ability: "gaunter_neutral_leader",
    filename: "Gaunter_Leader",
    count: "1",
  },
  {
    name: "Gaunter o'Dim",
    id: "1004-skel",
    deck: "skellige",
    row: "leader",
    strength: "0",
    ability: "gaunter_neutral_leader",
    filename: "Gaunter_Leader",
    count: "1",
  },
  {
    name: "Gaunter o'Dim",
    id: "1004-sky",
    deck: "sky",
    row: "leader",
    strength: "0",
    ability: "gaunter_neutral_leader",
    filename: "Gaunter_Leader",
    count: "1",
  },
  {
    name: "Gaunter o'Dim",
    id: "1004-synd",
    deck: "syndicate",
    row: "leader",
    strength: "0",
    ability: "gaunter_neutral_leader",
    filename: "Gaunter_Leader",
    count: "1",
  },
  {
    name: "Gaunter O'Dimm — Master of Time",
    id: "1004-1-mon",
    deck: "monsters",
    row: "leader",
    strength: "0",
    ability: "time_round_reverse",
    filename: "Gaunter_Leader2",
    count: "1",
  },
  {
    name: "Gaunter O'Dimm — Master of Time",
    id: "1004-1-nilf",
    deck: "nilfgaard",
    row: "leader",
    strength: "0",
    ability: "time_round_reverse",
    filename: "Gaunter_Leader2",
    count: "1",
  },
  {
    name: "Gaunter O'Dimm — Master of Time",
    id: "1004-1-realms",
    deck: "realms",
    row: "leader",
    strength: "0",
    ability: "time_round_reverse",
    filename: "Gaunter_Leader2",
    count: "1",
  },
  {
    name: "Gaunter O'Dimm — Master of Time",
    id: "1004-1-scol",
    deck: "scoiatael",
    row: "leader",
    strength: "0",
    ability: "time_round_reverse",
    filename: "Gaunter_Leader2",
    count: "1",
  },
  {
    name: "Gaunter O'Dimm — Master of Time",
    id: "1004-1-skel",
    deck: "skellige",
    row: "leader",
    strength: "0",
    ability: "time_round_reverse",
    filename: "Gaunter_Leader2",
    count: "1",
  },
  {
    name: "Gaunter O'Dimm — Master of Time",
    id: "1004-1-sky",
    deck: "sky",
    row: "leader",
    strength: "0",
    ability: "time_round_reverse",
    filename: "Gaunter_Leader2",
    count: "1",
  },
  {
    name: "Gaunter O'Dimm — Master of Time",
    id: "1004-1-synd",
    deck: "syndicate",
    row: "leader",
    strength: "0",
    ability: "time_round_reverse",
    filename: "Gaunter_Leader2",
    count: "1",
  },
  {
    name: "Ida Emean — Elven Divination",
    id: "1003", // Replaced id from Jan Calveit: Calculated Recovery
    deck: "scoiatael",
    row: "leader",
    strength: "0",
    ability: "d20cloner",
    filename: "Ida_Emean_d20",
    count: "1",
  },
  {
    name: "Spice Merchant",
    id: "1005",
    deck: "realms",
    row: "close",
    strength: "-5",
    ability: "hero sabotage",
    filename: "spice_trader",
    count: "1",
    //  reinforce: { owner_name: "Temeria", spawn_count: 0 }
  },
  {
    name: "Roach",
    id: "1006",
    deck: "neutral",
    row: "close",
    strength: "1",
    ability: "powergain",
    filename: "roach",
    count: "1",
  },
  {
    name: "Axii",
    id: "1007",
    deck: "neutral",
    row: "close",
    strength: "0",
    ability: "hero axii2_desc",
    filename: "axii",
    count: "0",
  },
  {
    name: "Lambert",
    id: "1008",
    deck: "neutral",
    row: "close",
    strength: "9",
    ability: "hero axii",
    filename: "lambert",
    count: "1",
  },
  {
    name: "Eskel",
    id: "1009",
    deck: "neutral",
    row: "close",
    strength: "6",
    ability: "hero avenger",
    filename: "eskel",
    count: "1",
  },
  {
    name: "Griffin School Witcher",
    id: "1010",
    deck: "neutral",
    row: "agile",
    strength: "5",
    ability: "gryffinSchool DontPickMeUp",
    filename: "GryffinWitcher",
    count: "2",
  },
  {
    name: "Conjunction of the Spheres",
    id: "1011",
    deck: "neutral",
    row: "siege",
    strength: "0",
    ability: "magicthegathering DontPickMeUp",
    filename: "cos",
    count: "3",
  },
  {
    name: "witcher Signs: Axii",
    id: "1011",
    deck: "neutral",
    row: "close",
    strength: "0",
    ability: "hero axii2_desc_playable",
    filename: "axii_p",
    count: "0",
    witcher_sign: true,
  },
  {
    name: "Vattier de Rideaux",
    id: "1012",
    deck: "nilfgaard",
    row: "close",
    strength: "-5",
    ability: "hero sabotage",
    filename: "sab",
    count: "1",
  },
  {
    name: "Iorveth",
    id: "1013",
    deck: "scoiatael",
    row: "ranged",
    strength: "-5",
    ability: "hero sabotage",
    filename: "scol_sab",
    count: "1",
  },
  {
    name: "Birna Bran - Sabotage",
    id: "1014",
    deck: "skellige",
    row: "siege",
    strength: "-5",
    ability: "hero sabotage",
    filename: "bad_lady",
    count: "1",
  },
  {
    name: "Beast Of Tussant",
    id: "1015",
    deck: "monsters",
    row: "agile",
    strength: "-5",
    ability: "hero sabotage",
    filename: "beast_of_tussant",
    count: "1",
  },
  {
    name: "Dopler",
    id: "1016",
    deck: "neutral",
    row: "siege",
    strength: "0",
    ability: "dopler",
    filename: "dopler",
    count: "2",
  },
  {
    name: "Dopler Revealed",
    id: "1017",
    deck: "neutral",
    row: "ranged",
    strength: "-6",
    ability: "hero",
    filename: "reveal_dopler",
    count: "0",
    avenger: "HiIamDopler",
  },
  {
    name: "Witcher - Quen",
    id: "1018",
    deck: "neutral",
    row: "close",
    strength: "0",
    ability: "wshield DontPickMeUp",
    filename: "wshield",
    count: "2",
  },
  {
    name: "Witcher Signs: Quen",
    id: "1019",
    deck: "neutral",
    row: "agile",
    strength: "0",
    ability: "hero wshield DontPickMeUp quen_desc",
    filename: "quen",
    count: "0",
    witcher_sign: true,
  },
  {
    name: "Eist Tuirseach — King Of Citra",
    id: "1020",
    deck: "skellige",
    row: "leader",
    strength: "",
    ability: "eist_tuirseach",
    filename: "eist_tuirseach",
    count: "0",
  },
  {
    name: "Svalblod Cult",
    id: "1021",
    deck: "skellige",
    row: "leader",
    strength: "",
    ability: "skellige_berserk_reward",
    filename: "svalblod",
    count: "0",
  },
  {
    name: "Svalblod Cult - Transformation",
    id: "1022",
    deck: "skellige",
    row: "agile",
    strength: "0",
    ability: "hero mardroeme",
    filename: "svalblod_change",
    count: "0",
  },
  {
    name: "Arnjolf the Patricide",
    id: "1023",
    deck: "skellige",
    row: "leader",
    strength: "",
    ability: "skellige_bond_summoner",
    filename: "Arnjolf_the_Patricide",
    count: "0",
  },
  {
    name: "Witcher Signs: Aard",
    id: "1024",
    deck: "neutral",
    row: "agile",
    strength: "-3",
    ability: "hero aard",
    filename: "aard",
    count: "0",
    witcher_sign: true,
  },
  {
    name: "Witcher Signs: Yrden",
    id: "1025",
    deck: "neutral",
    row: "ranged",
    strength: "0",
    ability: "yrden",
    filename: "yrden",
    count: "0",
    witcher_sign: true,
  },
  {
    name: "Witcher Signs: Ignii",
    id: "1026",
    deck: "neutral",
    row: "close",
    strength: "-2",
    ability: "hero resilience_igni",
    filename: "igni",
    count: "0",
    witcher_sign: true,
  },
  {
    name: "Udalryk an Brokvar — Gods Choosen",
    id: "1027",
    deck: "skellige",
    row: "leader",
    strength: "",
    ability: "turn_skiper",
    filename: "udalryka_leader",
    count: "0",
  },
  {
    name: "Tactical Forecaster — Kaedwen Division",
    id: "1028",
    deck: "realms",
    row: "leader",
    strength: "",
    ability: "keadwen_weather",
    filename: "keadwen_weather",
    count: "0",
  },
  {
    name: "Radovid V the Stern — In Madness",
    id: "1029",
    deck: "realms",
    row: "leader",
    strength: "",
    ability: "scorchstopper",
    filename: "radovid_stern",
    count: "0",
  },
  {
    name: "False Ciri — Empress of Nilfgaard",
    id: "1030",
    deck: "nilfgaard",
    row: "leader",
    strength: "",
    ability: "turn_skiper",
    filename: "fake_ciri",
    count: "0",
  },
  {
    name: "White Frost",
    id: "1031",
    deck: "weather",
    row: "",
    strength: "",
    ability: "frost fog",
    filename: "whitefrost",
    count: "3",
  },
  {
    name: "Temeria",
    id: "1032",
    deck: "realms",
    row: "close",
    strength: "0",
    ability: "hero reinforce",
    filename: "temeriacall",
    count: "0",
  },
  {
    name: "Blue Stripe Commando — Scout",
    id: "1033",
    deck: "realms",
    row: "close",
    strength: "0",
    ability: "hero morale",
    filename: "temeriamoral",
    count: "0",
    reinforce: { owner_name: "temeriacall", spawn_count: 2 },
  },
  {
    name: "Blue Stripe Commando — Soldier",
    id: "1034",
    deck: "realms",
    row: "close",
    strength: "1",
    ability: "bond",
    filename: "temeriabluestripe",
    count: "0",
    reinforce: { owner_name: "temeriacall", spawn_count: 1 },
  },
  {
    name: "Blue Stripe Commando — Soldier",
    id: "1034",
    deck: "realms",
    row: "close",
    strength: "1",
    ability: "bond",
    filename: "temeriabluestripe_2",
    count: "0",
    reinforce: { owner_name: "temeriacall", spawn_count: 1 },
  },
  {
    name: "Blue Stripe Commando — Quen",
    id: "1035",
    deck: "realms",
    row: "close",
    strength: "0",
    ability: "hero wshield",
    filename: "temeriamoral_1",
    count: "0",
    witcher_sign: false,
    reinforce: { owner_name: "temeriacall", spawn_count: 1 },
  },
  {
    name: "Vernon Roche — Blue Stripes Commando Leader",
    id: "1036",
    deck: "realms",
    row: "leader",
    strength: "",
    ability: "temeria_call",
    filename: "vernontemeria_call",
    count: "0",
  },
  // Custom faction or something
  {
    name: "Hopeful Steward",
    id: "3001",
    deck: "sky",
    row: "agile",
    strength: "7",
    ability: "hero morale",
    filename: "steward",
    count: "1",
  },
  {
    name: "Royal Guard",
    id: "3002",
    deck: "sky",
    row: "close",
    strength: "3",
    ability: "muster",
    filename: "guard",
    count: "3",
  },
  {
    name: "Chibi Mask",
    id: "3003",
    deck: "sky",
    row: "ranged",
    strength: "1",
    ability: "bond",
    filename: "chibi_mask",
    count: "3",
  },
  {
    name: "Dark Dragon",
    id: "3004",
    deck: "sky",
    row: "ranged",
    strength: "5",
    ability: "",
    filename: "krill",
    count: "3",
  },
  {
    name: "Cackling Cannoneer",
    id: "3005",
    deck: "sky",
    row: "siege",
    strength: "7",
    ability: "scorch_s",
    filename: "rico",
    count: "1",
  },
  {
    name: "Wandering Carnival",
    id: "3006",
    deck: "sky",
    row: "siege",
    strength: "6",
    ability: "",
    filename: "arcadaoffun",
    count: "2",
  },
  {
    name: "Fortune Drum",
    id: "3007",
    deck: "sky",
    row: "agile",
    strength: "0",
    ability: "hero morale",
    filename: "fortunedrum",
    count: "0",
  },
  {
    name: "Ascended Ancestor Spirit",
    id: "3008",
    deck: "sky",
    row: "close",
    strength: "2",
    ability: "bond",
    filename: "spirit",
    count: "2",
  },
  {
    name: "Sky Kid - Danielle",
    id: "3009",
    deck: "sky",
    row: "close",
    strength: "4",
    ability: "morale",
    filename: "danielle",
    count: "1",
    "@Discord": "1359183163355693347",
  },
  {
    name: "Red Crab",
    id: "3010",
    deck: "sky",
    row: "siege",
    strength: "4",
    ability: "morale",
    filename: "redcrab",
    count: "2",
  },
  {
    name: "Spy Crab",
    id: "3011",
    deck: "sky",
    row: "agile",
    strength: "3",
    ability: "spy",
    filename: "crabspy",
    count: "2",
  },
  {
    name: "Darkness Storm",
    id: "3012",
    deck: "sky",
    row: "close",
    strength: "0",
    ability: "hero darkstormegen",
    filename: "darkstorm",
    count: "0",
  },
  {
    name: "darkness_storm_leader",
    id: "3013",
    deck: "sky",
    row: "leader",
    strength: "0",
    ability: "darkness_storm_leader",
    filename: "darkness_storm_leader",
    count: "1",
  },
  {
    name: "Reassuring Ranger",
    id: "3014",
    deck: "sky",
    row: "agile",
    strength: "4",
    ability: "medic",
    filename: "ranger",
    count: "1",
  },
  {
    name: "20 Years Of That Game Comapny",
    id: "3015",
    deck: "sky",
    row: "siege",
    strength: "0",
    ability: "tgc_portal DontPickMeUp",
    filename: "tgc20",
    count: "2",
  },
  {
    name: "wasteland Elder",
    id: "3016",
    deck: "sky",
    row: "leader",
    strength: "0",
    ability: "eredin_commander",
    filename: "elder_wasteland",
    count: "1",
  },
  {
    name: "Days Of Color Guide",
    id: "3017",
    deck: "sky",
    row: "agile",
    strength: "1",
    ability: "reinforce DontPickMeUp",
    filename: "colorguide",
    count: "1",
  },
  {
    name: "Trevor Project",
    id: "3018",
    deck: "sky",
    row: "ranged",
    strength: "2",
    ability: "hero",
    filename: "colorcollab",
    count: "0",
    reinforce: { owner_name: "colorguide", spawn_count: 2 },
  },
  {
    name: "Aviary Village Emotional Support",
    id: "3019",
    deck: "sky",
    row: "siege",
    strength: "3",
    ability: "medic",
    filename: "aviary_medic",
    count: "1",
    discord: "1074082782998966342",
  },
  {
    name: "Elder of the Vault — Two Embers",
    id: "3030",
    deck: "sky",
    row: "leader",
    strength: "",
    ability: "turn_skiper",
    filename: "vault_elder_s2e",
    count: "0",
  },
  {
    name: "Fisstech",
    id: "4001",
    deck: "syndicate",
    row: "agile",
    strength: "3",
    ability: "morale",
    filename: "fisstech",
    count: "2",
  },
  {
    name: "Sigi Reuven",
    id: "4002",
    deck: "syndicate",
    row: "leader",
    strength: "0",
    ability: "mediclove",
    filename: "sigi_reuven",
    count: "0",
  },
  {
    name: "King of Begger",
    id: "4003",
    deck: "syndicate",
    row: "leader",
    strength: "0",
    ability: "emhyr_whiteflame2",
    filename: "king_of_beggers",
    count: "0",
  },
  {
    name: "Days Of Nature Guide",
    id: "3031",
    deck: "sky",
    row: "agile",
    strength: "1",
    ability: "reinforce DontPickMeUp",
    filename: "natureguide",
    count: "1",
  },
  {
    name: "The Ocean Cleanup",
    id: "3032",
    deck: "sky",
    row: "siege",
    strength: "4",
    ability: "morale",
    filename: "naturecollab",
    count: "0",
    reinforce: { owner_name: "natureguide", spawn_count: 1 },
  },
  {
    name: "Sky Anniversary",
    id: "3033",
    deck: "sky",
    row: "ranged",
    strength: "3",
    ability: "morale",
    filename: "skyfest",
    count: "1",
  },
  {
    name: "Magister",
    id: "4004",
    deck: "syndicate",
    row: "agile",
    strength: "6",
    ability: "hero scorch_a",
    filename: "magister",
    count: "1",
  },
  {
    name: "Circle of Elements",
    id: "1037",
    deck: "neutral",
    row: "siege",
    strength: "1",
    ability: "powergain",
    filename: "custom!power_place",
    count: "1",
    customassets: {
      lg: {
        hero: false,
        ability: "powergain",
        name: [
          "Circle of Elements: Quen",
          "Circle of Elements: Axii",
          "Circle of Elements: Igni",
          "Circle of Elements: Aard",
          "Circle of Elements: Yrden",
        ],
        desc: ["An Place of Power...."],
        txt_timed_a: true,
      },
      sm: {
        type: "timed_a", // url/build/timed
        build: [],
        url: null,
        timed: [
          "img/sm/power_place/quen.jpg",
          "img/sm/power_place/axii.jpg",
          "img/sm/power_place/igni.jpg",
          "img/sm/power_place/aard.jpg",
          "img/sm/power_place/yrden.jpg",
        ],
      },
    },
  },
  {
    note: "this is  _replace_me like card, arrive.bin will update it, if you are doing custom server and dont want it, remove this card!",
    name: "Traveling Spirit",
    id: "3034",
    deck: "sky",
    row: "agile",
    strength: "5",
    ability: "",
    filename: "custom!traveling_spirit",
    count: "0",
    count_monitor: {
      base: 2, // not really doing anything, the base value
      monitor: "ts",
      id: "ts_count",
      duration: { start: "null", duration: "1" },
    },
    customassets: {
      lg: {
        hero: false,
        ability: "agile",
        name: "Traveling spirit",
        desc: "A special guest from times long gone...",
        txt_timed_a: false,
      },
      sm: {
        type: "ts", // url/build/timed
        build: [],
        url: null,
        timed: [],
      },
    },
  },
  { _replace_me: "sky_season" },
  { _replace_me: "randomcards" },
  {
    name: "Vincent Van Gogh",
    id: "3035",
    deck: "sky",
    row: "close",
    strength: "5",
    ability: "hero reinforce",
    filename: "custom!sky_vincent",
    count: "1",
    customassets: {
      lg: {
        hero: true,
        ability: "reinforce",
        name: "Vincent Van Gogh",
        desc: "The world knows the legend.\nFew know the full story.",
        txt_timed_a: false,
      },
      sm: {
        type: "url", // url/build/timed
        build: [],
        url: "img/sm/dear_van_gogh/vincent.jpg",
        timed: [],
      },
    },
  },
  {
    name: "Vincent Van Gogh: Painting",
    id: "3036", // Keep sky  faction ID
    deck: "neutral",
    row: "ranged",
    strength: "1",
    ability: "powergain",
    filename: "custom!vincent_painting_power",
    count: "0",
    customassets: {
      lg: {
        hero: false,
        ability: "powergain",
        name: [
          "The Starry Night",
          "Irises",
          "Bedroom in Arles",
          "Vase with Twelve Sunflowers",
        ],
        desc: [
          "A thousand lights defied the dark.",
          "Grace blooms where silence lingers.",
          "Home is where the heart dares to rest.",
          "A dozen suns, forever in bloom.",
        ],
        txt_timed_a: true,
      },
      sm: {
        type: "timed_a", // url/build/timed
        build: [],
        url: null,
        timed: [
          "img/sm/dear_van_gogh/switching/starry_night.jpg",
          "img/sm/dear_van_gogh/switching/iris.jpg",
          "img/sm/dear_van_gogh/switching/bedroom.jpg",
          "img/sm/dear_van_gogh/switching/vase_of_flowers.jpg",
        ],
      },
    },
    reinforce: { owner_name: "custom!sky_vincent", spawn_count: 1 },
  },
  {
    name: "Dear Van Gogh — Seasonal Spirits",
    id: "3037",
    deck: "sky",
    row: "ranged",
    strength: "3",
    ability: "bond",
    filename: "custom!sky_vincent_guys",
    count: "3",
    //  count_monitor: {
    //    base: 3,
    //    monitor: "based",
    //    id: "vincent_seasonal_spirits",
    //     duration: {
    //       start: "2026-07-17T07:00:00.000Z",
    //       duration: "9999999999999999999999999",
    //     },
    //   },// Noted out so i have template for future
    customassets: {
      lg: {
        hero: false,
        ability: "bond",
        name: "Dear Van Gogh — Seasonal Spirits",
        desc: "Seasonal Spirits and their stories can take various forms.",
        txt_timed_a: false,
      },
      sm: {
        type: "url", // url/build/timed
        build: [],
        url: "img/sm/dear_van_gogh/seasonal_travelers.jpg",
        timed: [],
      },
    },
  },
  {
    name: "Dear Van Gogh — Seasonal Hearth",
    id: "3038",
    deck: "sky",
    row: "close",
    strength: "2",
    ability: "medic",
    filename: "custom!sky_vincent_medic",
    count: "1",
    customassets: {
      lg: {
        hero: false,
        ability: "medic",
        name: "Dear Van Gogh — Seasonal Hearth",
        desc: "Every ember remembers the sun.",
        txt_timed_a: false,
      },
      sm: {
        type: "url", // url/build/timed
        build: [],
        url: "img/sm/dear_van_gogh/vincent_medic.jpg",
        timed: [],
      },
    },
  },
  {
    name: "Hym",
    id: "1038",
    deck: "monsters",
    row: "ranged",
    strength: "0",
    ability: "medic_n",
    filename: "hym",
    count: "2",
  },
  {
    name: "Moonlight",
    id: "1039",
    deck: "monsters",
    row: "agile",
    strength: "2",
    ability: "morale",
    filename: "custom!m_moonlight",
    count: "2",
    customassets: {
      lg: {
        hero: false,
        ability: "morale",
        name: "Moonlight",
        desc: "What a beautiful phenomenon...\nAnd how deadly.",
        txt_timed_a: false,
      },
      sm: {
        type: "moon", // url/build/timed
        build: [],
        url: null,
        timed: [],
      },
    },
  },
  {
    name: "Night Over Novigrad",
    id: "1039",
    deck: "syndicate",
    row: "siege",
    strength: "3",
    ability: "morale",
    filename: "custom!s_moonlight",
    count: "2",
    customassets: {
      lg: {
        hero: false,
        ability: "morale",
        name: "Night Over Novigrad",
        desc: "All manner of filth spills out onto the roads at night.",
        txt_timed_a: false,
      },
      sm: {
        type: "moon", // url/build/timed
        build: [],
        url: null,
        timed: [],
      },
    },
  },
  {
    name: "Full Moon",
    id: "1040",
    deck: "neutral",
    row: "siege",
    strength: "-1",
    ability: "reinforce DontPickMeUp",
    filename: "custom!deatheatersmoon",
    count: "0",
    count_monitor: {
      base: 1, // not really doing anything, the base value
      monitor: "fullmoon",
      id: "id.foolmoon",
      duration: { start: "null", duration: "1" },
    },
    customassets: {
      lg: {
        hero: false,
        ability: "reinforce",
        name: "Full Moon",
        desc: "Blood-curdling screams\nCarried by the cool breath of the night wind",
        txt_timed_a: false,
      },
      sm: {
        type: "moon", // url/build/timed
        build: [],
        url: null,
        timed: [],
      },
    },
  },
  {
    name: "New Moon",
    id: "1041",
    deck: "neutral",
    row: "siege",
    strength: "-1",
    ability: "reinforce DontPickMeUp",
    filename: "custom!nightwraithsmoon",
    count: "0",
    count_monitor: {
      base: 1, // not really doing anything, the base value
      monitor: "newmoon",
      id: "id.newmoon",
      duration: { start: "null", duration: "1" },
    },
    customassets: {
      lg: {
        hero: false,
        ability: "reinforce",
        name: "New Moon",
        desc: "Empty Sky...\nMoonless Sky...",
        txt_timed_a: false,
      },
      sm: {
        type: "moon", // url/build/timed
        build: [],
        url: null,
        timed: [],
      },
    },
  },
  {
    name: "Nightwraith",
    id: "1042",
    deck: "monsters",
    row: "ranged",
    strength: "4",
    ability: "",
    filename: "nightwraith",
    count: "2",
    reinforce: { owner_name: "custom!nightwraithsmoon", spawn_count: 2 },
  },
  {
    name: "Noonwraith",
    id: "1042",
    deck: "monsters",
    row: "ranged",
    strength: "4",
    ability: "",
    filename: "noonwraith",
    count: "2",
  },
  {
    name: "Necrophages",
    id: "1043",
    deck: "monsters",
    row: "close",
    strength: "3",
    ability: "",
    filename: "deatheatr",
    count: "0",
    reinforce: { owner_name: "custom!deatheatersmoon", spawn_count: 3 },
  },
  {
    name: "Wardancer",
    id: "1044",
    deck: "scoiatael",
    row: "all",
    strength: "4",
    ability: "",
    filename: "wardancer",
    count: "2",
  },
  {
    name: "Elders of the Valley",
    id: "3039",
    deck: "sky",
    row: "leader",
    strength: "",
    ability: "francesca_beautiful",
    filename: "valley_twins",
    count: "0",
  },
  {
    name: "Chill Sunbather with a bow in thier hair",
    id: "3039",
    deck: "sky",
    row: "agile",
    strength: "5",
    ability: "",
    filename: "sunbather_pink",
    count: "1",
    discord: "707982033208475759",
  },
  {
    name: "Blue Feather",
    id: "3040",
    deck: "sky",
    row: "siege",
    strength: "0",
    ability: "avenger DontPickMeUp",
    filename: "bluebird_a",
    count: "1",
    avenger: "bluebird_sad",
  },
  {
    name: "Blue Bird",
    id: "3041",
    deck: "sky",
    row: "ranged",
    strength: "7",
    ability: "hero reinforce",
    filename: "bluebird_b",
    count: "0",
    avenger: "bluebird_a",
  },
  {
    name: "Sad Child",
    id: "3042",
    deck: "sky",
    row: "siege",
    strength: "1",
    ability: "",
    filename: "bluebird_sad",
    count: "0",
    reinforce: { owner_name: "bluebird_b", spawn_count: 1 },
  },
  {
    name: "The Devil",
    id: "1045",
    deck: "neutral",
    row: "siege",
    strength: "0",
    ability: "thedevil",
    filename: "thedevil",
    count: "3",
  },
  {
    name: "Eredin — The Elder Blood Pursuer",
    id: "1046",
    deck: "monsters",
    row: "leader",
    strength: "",
    ability: "bucket",
    filename: "eredin_bucket",
    count: "0",
  },
];
let pickedfakecard = { a: false, b: null };

var card_dict = deepClone(card_dict_base);
loadingscreenupdate(`Translating cards!`);
card_dict = translateCardDict();
// Moonlight and etc card timer setup un custom_cards.js

loadingscreenupdate(`Loaded ${card_dict.length} cards!`);

const witcher_signs = Object.entries(card_dict)
  .filter(([_, card]) => card.witcher_sign)
  .sort(([, a], [, b]) => a.name.localeCompare(b.name))
  .map(([key, card]) => ({
    id: key,
    ...card,
  }));

loadingscreenupdate(`Loaded ${witcher_signs.length} witcher signs!`);
console.log("Cards array", card_dict, witcher_signs);

function setupSpiritTimer(card, data) {
  card.count_monitor = {
    base: data.when.card_count,
    monitor: "based",
    id: "ts_count",
    duration: {
      start: data.when.arrive,
      duration: Number(data.when.duration),
    },
    msg: true,

    msg_data: {
      msg: getTranslation("ui.notif_side.ts").replace(
        "%s",
        data.when.spirit_name,
      ),
      display: 13000,
    },
  };

  pushTimedCount(card);

  console.log("[SPIRIT TIMER SETUP]", card.name, card.count_monitor);
}

function pushMessage(msg, display = 5000) {
  active_messages.push({
    id: crypto.randomUUID(),
    msg,
    start: Clock.now(),
    display,
  });

  updateMessageBox();
  scheduleUpdate();
}
function showsync(duration) {
  pushMessage(
    formatMessage2(getUiStrng("sync.sidenotif").replace("%s", duration / 1000)),
    duration,
  );
}
function scheduleUpdate() {
  if (expireTimer) {
    clearTimeout(expireTimer);
    expireTimer = null;
  }

  if (active_messages.length === 0) {
    updateMessageBox();
    return;
  }

  const now = Clock.now();

  // Find the soonest expiration
  const nextExpire = Math.min(
    ...active_messages.map((msg) => msg.start + msg.display),
  );

  const delay = Math.max(0, nextExpire - now);

  expireTimer = setTimeout(removeExpiredMessages, delay);
}

function removeExpiredMessages() {
  const now = Clock.now();

  active_messages = active_messages.filter((message) => {
    const expired = Clock.now() >= message.start + message.display;

    if (expired && message.element) {
      message.element.remove();
      message.element = null;
    }

    return !expired;
  });

  updateMessageBox();
  scheduleUpdate();
}
function scanMessages() {
  if (active_messages.length === 0) {
    return "OK";
  }
  let now = Clock.now();

  active_messages = active_messages.filter((message) => {
    return now < message.start + message.display;
  });

  updateMessageBox();
}
function formatMessage(template, card, timer) {
  let end = timer.start + timer.duration;

  let msg = escapeHtml(template);

  // Restore placeholders
  msg = msg.replaceAll("&lt;$card&gt;", escapeHtml(card.name));
  msg = msg.replaceAll("&lt;$duration&gt;", formatDuration(timer.duration));
  msg = msg.replaceAll("&lt;$enddatelocal&gt;", formatLocalDate(end));

  // New lines
  msg = msg.replaceAll("\n", "<br>");

  // Restore <color=#xxxxxx>...</color>
  msg = msg.replace(
    /&lt;color=(#[0-9a-fA-F]{3,6})&gt;([\s\S]*?)&lt;\/color&gt;/g,
    '<span style="color:$1">$2</span>',
  );

  return msg;
}
function formatMessage2(template) {
  let msg = escapeHtml(template);
  // New lines
  msg = msg.replaceAll("\n", "<br>");

  // Restore <color=#xxxxxx>...</color>
  msg = msg.replace(
    /&lt;color=(#[0-9a-fA-F]{3,6})&gt;([\s\S]*?)&lt;\/color&gt;/g,
    '<span style="color:$1">$2</span>',
  );

  return msg;
}
function formatDuration(ms) {
  let total = Math.floor(ms / 1000);

  let d = Math.floor(total / 86400);
  total %= 86400;

  let h = Math.floor(total / 3600);
  total %= 3600;

  let m = Math.floor(total / 60);

  let parts = [];

  if (d) parts.push(`${d}d`);
  if (h) parts.push(`${h}h`);
  if (m || parts.length === 0) parts.push(`${m}m`);

  return parts.join(" ");
}
function formatLocalDate(timestamp) {
  return new Date(timestamp).toLocaleString();
}
function createMessageElement(message) {
  const item = document.createElement("div");
  item.className = "message-item";

  item.innerHTML = `
    <div class="message-text">${message.msg}</div>
    <div class="message-progress">
      <div class="message-progress-fill"></div>
    </div>
  `;

  const fill = item.querySelector(".message-progress-fill");

  fill.style.width = "100%";

  activeBars.add({
    fill,
    start: performance.now(),
    duration: message.display,
  });

  return item;
}
function updateMessageBox() {
  const box = document.getElementById("message-box");
  if (!box) return;

  // Remove DOM nodes that no longer belong
  for (const child of [...box.children]) {
    if (!active_messages.some((msg) => msg.element === child)) {
      child.remove();
    }
  }

  // Add any new ones
  for (const message of active_messages) {
    if (!message.element) {
      message.element = createMessageElement(message);
    }

    if (!message.element.parentNode) {
      box.appendChild(message.element);
    }
  }

  box.style.display = active_messages.length ? "block" : "none";
}

function pushTimedCount(card) {
  if (!card.count_monitor) return;
  if (card.count_monitor.monitor !== "based") return;

  let timer = {
    card_id: card.id,
    monitor_id: card.count_monitor.id,
    start: new Date(card.count_monitor.duration.start).getTime(),
    duration: Number(card.count_monitor.duration.duration) * 1000,
    activated: false,
    _card: card,
  };

  timed_count_change.push(timer);

  console.log("[TIMER ADDED]", timer);
}

// Scan timers
function scanTimedCountChange() {
  let now = Clock.now();
  timed_count_change.forEach((timer, index) => {
    let card = card_dict.find((c) => c.id === timer.card_id);

    if (!card) {
      console.log("[ERROR] Card missing", timer.card_id);
      return;
    }
    const end = timer.start + timer.duration;

    // Start time reached
    if (!timer.activated && now >= timer.start && now < end) {
      card.count = card.count_monitor.base;

      timer.activated = true;
      console.log("Active", card, card.count_monitor.msg);
      if (card.count_monitor.msg) {
        pushMessage(
          formatMessage(card.count_monitor.msg_data.msg, card, timer),
          card.count_monitor.msg_data.display,
        );
      }

      console.log(
        "[ACTIVATED] [TMR]",
        card.name,
        "count:",
        card.count,
        "monitor:",
        timer.monitor_id,
        JSON.stringify(card),
        card,
      );
    }

    // Duration finished
    if (timer.activated && now >= end) {
      card.count = 0;

      console.log(
        "[EXPIRED] [TMR]",
        card.name,
        "count reset to:",
        card.count,
        JSON.stringify(card),
        card,
      );

      // remove timer
      timed_count_change.splice(index, 1);
    }
  });
}

// Run every second
setInterval(scanTimedCountChange, 1000);
//setInterval(scanMessages, 100);

async function notifyLocalhost(timedCount) {
  const url = "http://localhost:8080/api/recivethat";

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        timed_count_change: timedCount,
      }),
    });

    if (!res.ok) {
      throw new Error(`${res.status} ${res.statusText}`);
    }

    console.log(`✓ Sent timed_count_change=${timedCount} to ${url}`);
  } catch (err) {
    console.log("Local API not available, skipping notification.");
  }
}
