name: Sync to second repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Push to second repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TARGET_REPO_TOKEN }}
        with:
          source-directory: "."
          destination-github-username: TheRedMineword
          destination-repository-name: gwent.localplayer.dev
          user-email: your@email.com
          target-branch: main
